---
- name: Install nginx and certbot
  apt:
    name:
      - nginx
      - certbot
    state: present
    update_cache: yes

- name: Remove default site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Ensure ACME webroot
  file:
    path: /var/www/letsencrypt
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'

- name: Add bg_color log format
  template:
    src: bg_color_log.conf.j2
    dest: "/etc/nginx/conf.d/bg_color_log.conf"
    mode: '0644'

- name: Write upstream snippet
  template:
    src: upstream.conf.j2
    dest: "/etc/nginx/conf.d/{{ app_name }}-upstream.conf"
    mode: '0644'
  vars:
    upstream_ip: "{{ hostvars[groups[active_color][0]].ansible_host }}"
    upstream_port: "{{ app_port }}"
  register: upstream_tpl

- name: Write site (HTTP-only)
  template:
    src: site-http.conf.j2
    dest: "/etc/nginx/sites-available/{{ app_name }}.conf"
    mode: '0644'
  register: site_http_tpl

- name: Enable site
  file:
    src: "/etc/nginx/sites-available/{{ app_name }}.conf"
    dest: "/etc/nginx/sites-enabled/{{ app_name }}.conf"
    state: link
  register: enable_site

- name: nginx -t
  command: nginx -t
  changed_when: false
  register: nginx_test

- name: Fail if invalid nginx config
  fail:
    msg: "nginx config test failed: {{ nginx_test.stderr }}"
  when: nginx_test.rc != 0

- name: Reload nginx if changed
  service:
    name: nginx
    state: reloaded
  when: upstream_tpl.changed or site_http_tpl.changed or enable_site.changed
