---
- name: reload systemd
  systemd:
    daemon_reload: yes

- name: restart dotnet app
  systemd:
    unit: "{{ app_name }}"
    state: restarted
    enabled: yes
  
- name: restart nginx
  service:
    name: nginx
    state: restarted